/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.ADMIN;
import Model.NhanVien;
import Service.NhanVienService;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author PC
 */
public class QLNV extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(QLNV.class.getName());

    /**
     * Creates new form QLNV
     */
    public QLNV() {
        initComponents();
        customTable();
        getContentPane().setBackground(new java.awt.Color(135, 206, 235));
        loadNhanVien();
    }
    private void loadNhanVien() {
    NhanVienService service = new NhanVienService();
    ArrayList<NhanVien> list = service.getAllNhanVien();

    DefaultTableModel model = new DefaultTableModel();
    model.setColumnIdentifiers(new Object[]{
        "Mã NV", "Họ tên", "Giới tính", "SĐT", "Địa chỉ", "Chức vụ"
    });

    for (NhanVien nv : list) {
        model.addRow(new Object[]{
            nv.getMaNV(),
            nv.getHoTen(),
            nv.getGioiTinh(),
            nv.getSdt(),
            nv.getDiaChi(),
            nv.getChucVu()
        });
    }
    

    tblNhanVien.setModel(model);
}
private void customTable() {
    tblNhanVien.setRowHeight(30);
    tblNhanVien.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));

    tblNhanVien.getTableHeader().setFont(
        new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14)
    );

    tblNhanVien.getTableHeader().setBackground(java.awt.Color.BLACK);
    tblNhanVien.getTableHeader().setForeground(java.awt.Color.WHITE);

    tblNhanVien.setShowGrid(true);
    tblNhanVien.setGridColor(java.awt.Color.GRAY);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnQuayLai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblNhanVien);

        btnThem.setText("Thêm");
        btnThem.addActionListener(this::btnThemActionPerformed);

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(this::btnXoaActionPerformed);

        btnSua.setText("Sửa");
        btnSua.addActionListener(this::btnSuaActionPerformed);

        btnQuayLai.setText("Quay Lại");
        btnQuayLai.addActionListener(this::btnQuayLaiActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btnThem)
                        .addGap(41, 41, 41)
                        .addComponent(btnXoa)
                        .addGap(37, 37, 37)
                        .addComponent(btnSua)
                        .addGap(38, 38, 38)
                        .addComponent(btnQuayLai))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnSua)
                    .addComponent(btnQuayLai))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
         int row = tblNhanVien.getSelectedRow();

    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên cần xóa!");
        return;
    }

    int maNV = Integer.parseInt(tblNhanVien.getValueAt(row, 0).toString());

    int confirm = JOptionPane.showConfirmDialog(
            this,
            "Bạn có chắc muốn xóa nhân viên này?",
            "Xác nhận xóa",
            JOptionPane.YES_NO_OPTION
    );

    if (confirm == JOptionPane.YES_OPTION) {
        NhanVienService service = new NhanVienService();

        boolean result = service.xoaNhanVien(maNV);

        if (result) {
            JOptionPane.showMessageDialog(this, "Xóa nhân viên thành công!");
            loadNhanVien();
        } else {
            JOptionPane.showMessageDialog(this, "Xóa nhân viên thất bại!");
        }
    }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
         ThemNhanVien dialog =
            new ThemNhanVien(this, true);

    dialog.setLocationRelativeTo(this);
    dialog.setVisible(true);

    loadNhanVien();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        int row = tblNhanVien.getSelectedRow();

    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên cần sửa!");
        return;
    }

    int maNV = Integer.parseInt(tblNhanVien.getValueAt(row, 0).toString());
    String hoTen = tblNhanVien.getValueAt(row, 1).toString();
    String gioiTinh = tblNhanVien.getValueAt(row, 2).toString();
    String sdt = tblNhanVien.getValueAt(row, 3).toString();
    String diaChi = tblNhanVien.getValueAt(row, 4).toString();
    String chucVu = tblNhanVien.getValueAt(row, 5).toString();

    NhanVien nv = new NhanVien(maNV, hoTen, gioiTinh, sdt, diaChi, chucVu);

    SuaNhanVienDialog dialog = new SuaNhanVienDialog(this, true, nv);
    dialog.setLocationRelativeTo(this);
    dialog.setVisible(true);

    loadNhanVien();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
          TrangChuAdmin tc = new TrangChuAdmin();
    tc.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new QLNV().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNhanVien;
    // End of variables declaration//GEN-END:variables
}
