/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.ADMIN;
import Model.SanPham;
import Service.SanPhamService;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author PC
 */
public class QLSP extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(QLSP.class.getName());

    /**
     * Creates new form QLSP
     */
    public QLSP() {
        initComponents();
                getContentPane().setBackground(new java.awt.Color(135, 206, 235));

         customTable();
         loadSanPham();
    }
   private void customTable() {
    tblSanPham.setRowHeight(30);
    tblSanPham.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));

    tblSanPham.getTableHeader().setFont(
        new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14)
    );

    tblSanPham.getTableHeader().setBackground(java.awt.Color.BLACK);
    tblSanPham.getTableHeader().setForeground(java.awt.Color.WHITE);

    tblSanPham.setShowGrid(true);
    tblSanPham.setGridColor(java.awt.Color.GRAY);
}

private void loadSanPham() {
    SanPhamService service = new SanPhamService();
    ArrayList<SanPham> list = service.getAllSanPham();

    DefaultTableModel model = new DefaultTableModel();
    model.setColumnIdentifiers(new Object[]{
        "Mã SP", "Tên SP", "Mã hãng", "Giá bán", "Số lượng", "Mô tả"
    });

    for (SanPham sp : list) {
        model.addRow(new Object[]{
            sp.getMaSP(),
            sp.getTenSP(),
            sp.getMaHang(),
            (sp.getGiaBan() / 1000000) + " triệu",
            sp.getSoLuong(),
            sp.getMoTa()
        });
    }

    tblSanPham.setModel(model);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        lblTieuDe = new javax.swing.JLabel();
        btnThem = new java.awt.Button();
        btnXoa = new java.awt.Button();
        btnSua = new java.awt.Button();
        btnQuayLai = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblSanPham);

        lblTieuDe.setText("Quản lí sản phẩm");

        btnThem.setActionCommand("Thêm");
        btnThem.setLabel("Thêm");
        btnThem.setName("Thêm"); // NOI18N
        btnThem.addActionListener(this::btnThemActionPerformed);

        btnXoa.setLabel("Xóa");
        btnXoa.addActionListener(this::btnXoaActionPerformed);

        btnSua.setLabel("Sửa");
        btnSua.addActionListener(this::btnSuaActionPerformed);

        btnQuayLai.setLabel("Quay Lại");
        btnQuayLai.addActionListener(this::btnQuayLaiActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(lblTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(btnQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(166, 166, 166))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTieuDe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        btnThem.getAccessibleContext().setAccessibleName("Thêm");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        ThemSanPham dialog = new ThemSanPham(this, true);
    dialog.setLocationRelativeTo(this);
    dialog.setVisible(true);

    loadSanPham();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int row = tblSanPham.getSelectedRow();

    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm cần xóa!");
        return;
    }

    int maSP = Integer.parseInt(tblSanPham.getValueAt(row, 0).toString());

    int confirm = JOptionPane.showConfirmDialog(
            this,
            "Bạn có chắc muốn xóa sản phẩm này?",
            "Xác nhận xóa",
            JOptionPane.YES_NO_OPTION
    );

    if (confirm == JOptionPane.YES_OPTION) {
        SanPhamService service = new SanPhamService();

        boolean result = service.xoaSanPham(maSP);

        if (result) {
            JOptionPane.showMessageDialog(this, "Xóa sản phẩm thành công!");
            loadSanPham();
        } else {
            JOptionPane.showMessageDialog(this, "Xóa sản phẩm thất bại!");
        }
    }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
         int row = tblSanPham.getSelectedRow();

    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm cần sửa!");
        return;
    }

    int maSP = Integer.parseInt(tblSanPham.getValueAt(row, 0).toString());
    String tenSP = tblSanPham.getValueAt(row, 1).toString();
    int maHang = Integer.parseInt(tblSanPham.getValueAt(row, 2).toString());
    double giaBan = Double.parseDouble(tblSanPham.getValueAt(row, 3).toString());
    int soLuong = Integer.parseInt(tblSanPham.getValueAt(row, 4).toString());
    String moTa = tblSanPham.getValueAt(row, 5).toString();

    SanPham sp = new SanPham(maSP, tenSP, maHang, giaBan, soLuong, moTa);

    SuaSanPham dialog = new SuaSanPham(this, true, sp);
    dialog.setLocationRelativeTo(this);
    dialog.setVisible(true);

    loadSanPham();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
           TrangChuAdmin tc = new TrangChuAdmin();
    tc.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new QLSP().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnQuayLai;
    private java.awt.Button btnSua;
    private java.awt.Button btnThem;
    private java.awt.Button btnXoa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JTable tblSanPham;
    // End of variables declaration//GEN-END:variables
}
