/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.ADMIN;


/**
 *
 * @author PC
 */
public class TrangChuAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TrangChuAdmin.class.getName());

    /**
     * Creates new form TrangChu
     */
    public TrangChuAdmin() {
        initComponents();
//        getContentPane().setBackground(new java.awt.Color(135, 206, 235));


    customUI();
    }
private void customUI() {
    setTitle("Trang chủ Admin");
//    setSize(900, 600);
    setLocationRelativeTo(null);
    setResizable(false);

    getContentPane().setBackground(new java.awt.Color(245, 247, 250));

  

    java.awt.Font buttonFont = new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 18);

    javax.swing.JButton[] buttons = {
        btnQLNV, btnQLSP, btnQLH, btnQLHD, btnQLPN, btnThoat
    };

    for (javax.swing.JButton btn : buttons) {
        btn.setFont(buttonFont);
        btn.setFocusPainted(false);
        btn.setForeground(java.awt.Color.WHITE);
        btn.setBackground(new java.awt.Color(37, 99, 235));
        btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
    }

    btnThoat.setBackground(new java.awt.Color(220, 38, 38));
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnQLNV = new javax.swing.JButton();
        btnQLSP = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnQLH = new javax.swing.JButton();
        btnQLHD = new javax.swing.JButton();
        btnQLPN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnQLNV.setText("Quản lý nhân viên");
        btnQLNV.addActionListener(this::btnQLNVActionPerformed);

        btnQLSP.setText("Quản lí sản phẩm");
        btnQLSP.addActionListener(this::btnQLSPActionPerformed);

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(this::btnThoatActionPerformed);

        btnQLH.setText("Quản lí hãng điện thoại ");
        btnQLH.addActionListener(this::btnQLHActionPerformed);

        btnQLHD.setText("Quản lí hóa đơn");
        btnQLHD.addActionListener(this::btnQLHDActionPerformed);

        btnQLPN.setText("Quản lí phiếu nhập");
        btnQLPN.addActionListener(this::btnQLPNActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQLSP, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQLH, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQLHD, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQLPN, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnQLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQLSP, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQLH, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQLHD, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnQLPN, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLNVActionPerformed
        QLNV qlnv = new QLNV();
        qlnv.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnQLNVActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnQLSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLSPActionPerformed
        QLSP qlsp = new QLSP();
        qlsp.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnQLSPActionPerformed

    private void btnQLHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLHActionPerformed
        QLHangDienThoai qlhdt = new QLHangDienThoai();
        qlhdt.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnQLHActionPerformed

    private void btnQLHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLHDActionPerformed
        QLDonHang qldh = new QLDonHang();
        qldh.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnQLHDActionPerformed

    private void btnQLPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLPNActionPerformed
        QLPhieuNhap qlpn = new QLPhieuNhap();
        qlpn.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnQLPNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TrangChuAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQLH;
    private javax.swing.JButton btnQLHD;
    private javax.swing.JButton btnQLNV;
    private javax.swing.JButton btnQLPN;
    private javax.swing.JButton btnQLSP;
    private javax.swing.JButton btnThoat;
    // End of variables declaration//GEN-END:variables
}
